export const IDENTITY_TOKENS = {
  USER_REPOSITORY: 'IDENTITY_USER_REPOSITORY',
  ROLE_REPOSITORY: 'IDENTITY_ROLE_REPOSITORY',
  PERMISSION_REPOSITORY: 'IDENTITY_PERMISSION_REPOSITORY',
  ID_GENERATOR: 'IDENTITY_ID_GENERATOR',
  PASSWORD_HASHING: 'IDENTITY_PASSWORD_HASHING',
  PASSWORD_POLICY: 'IDENTITY_PASSWORD_POLICY',
  PASSWORD_RESET_TOKEN: 'IDENTITY_PASSWORD_RESET_TOKEN',
  EMAIL_VERIFICATION_TOKEN: 'IDENTITY_EMAIL_VERIFICATION_TOKEN',
  TOOL_AVAILABILITY: 'IDENTITY_TOOL_AVAILABILITY',
};
